language: python

python:
    - "2.7"
    - "3.4"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.15-1.linux-64.sh
    - sudo sh lilypond-2.19.15-1.linux-64.sh --batch
    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib
    - python setup.py install

script:
    - python music21/test/testSingleCoreAll.py