language: python

python:
    - "2.7"
    - "3.4"

install:
    - pip install numpy
    - pip install matplotlib
    - pip install scipy
    - pip install -e . 

script:
    - python music21/test/testSingleCoreAll.py